### ISSUE TITLE
Single Point in Polygon and MultiPolygon causes runtime error with IsValid()

### ISSUE THREAD

**Issue by Den3** [peterstace/simplefeatures#58]
After constructing a polygon or multipolyon with `DisableAllValidations`, isValid causes runtime error. The error is from getting coordinates.

**Comment by peterstace** [comment]
I don't think this is strictly a bug, because `DisableAllValidations` gives the caveat that any operation may fail in unexpected ways (including a panic) when using it.

However, the whole point of `IsValid` is that it should work on geometries that are not valid. So I think we need to do a few things here:

- Add some tests to ensure that various types of invalid geometry will work correctly with `DisableAllValidations` and `IsValid`.
- Fix issues identifying from the above tests (including the single point for a polygon case).
- Update the documentation of `IsValid` and `DisableAllValidations` to indicate that they are safe to use together.
